services:
  chatgpt-cli:
    build: .
    volumes:
      - .:/app
      - ${XDG_CONFIG_HOME:-~/.config}/chatgpt-cli:/root/.config/chatgpt-cli
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONPATH=/app/src
    stdin_open: true
    tty: true