providers:
  - name: "openai"
    api_key: "abc"
  - name: "anthropic"
    api_key: "def"
model: "claude-3-sonnet-20240229"
temperature: 0.7
markdown: true
easy_copy: true
non_interactive: false
json_mode: false
use_proxy: false
proxy: "socks5://127.0.0.1:2080"
storage_format: "markdown"
embedding_model: "text-embedding-ada-002"
embedding_dimension: 1536
max_context_tokens: 3500
show_spinner: true
max_tokens: 1024
budget:
  enabled: true
  amount: 10.0
  duration: "monthly"
  user: "abc"
